# The URL the site will be built for
base_url = 'https://example.com'
description = "Frontend-Entwicklung für Websites, Shopify-Onlineshops, Web- und Cross Platform-Apps"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Which theme to use (located in /themes/)
theme = 'anpu'

taxonomies = [
    { name = 'categories' },
    { name = 'tags' },
]


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
anpu_menu_links = [
    { url = '$BASE_URL/tags/', name = 'Tags' },
    { url = '$BASE_URL/imprint/', name = 'Imprint' },
]

anpu_date_format = '%e %B %Y'

title = 'Tony Spegel'
title_separator = "|"  # set as |, -, _, etc
title_addition = "Frontend, Shopify, Web-Apps"
lang = 'de'
