# The URL the site will be built for
base_url = "https://example.com"
description = "Everything you need to make a static site engine in one binary."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
author = "Tony Spegel"
menu_links = [
    { url = "$BASE_URL/", name = "Home" },
    { url = "$BASE_URL/blog/", name = "Blog" },
]