# The URL the site will be built for
base_url = "https://example.com"
description = "Frontend-Entwicklung für Websites, Shopify-Onlineshops, Web- und Cross Platform-Apps"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

minify_html = true
title = "Tony Spegel"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

taxonomies = [
    {name = "tags", rss = true},
    {name = "categories", rss = true},
]

[extra]
author = "Tony Spegel"
menu_links = [
    { url = "$BASE_URL/", name = "Home", id="main-link--home" },
    { url = "$BASE_URL/blog/", name = "Blog", id="main-link--blog" },
    { url = "$BASE_URL/tags/", name = "Tags", id="main-link--tags" },
]

title_separator = "|"  # set as |, -, _, etc
title_addition = "Frontend, Shopify, Web-Apps"
